package form;

import DataBase.DataValidator;
import DataBase.MessageDialogHelper;
import dao.BaiXeDao;
import dao.TTBaiXeDao;
import dao.VeThangDao;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BaiXe;
import model.TTBaiXe;
import model.VeThang;
import util.ClockThread;
import util.LoaiVe;

//import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
public class FormQuanLyBaiXe extends javax.swing.JPanel {

    private FormMain parentForm;
    private DefaultTableModel tblModel;
    String str = "";
    private FormBaoCao formBaoCao;

    /**
     * Creates new form FormQuanLyBaiXe
     */
    public static String dataStatic, dataStatic1, dataStatic2, dataStatic3;

    public FormQuanLyBaiXe(FormBaoCao formBaoCao) {
        this.formBaoCao = formBaoCao;
        initComponents();
        initThoiGianBaiXe();
        initTable();
        baiXe();
    }

    private void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{
            "Thẻ Xe", "Biển số xe", "Thời Gian Vào", "Loại Xe", "Loai Vé"
        });
        tblBaiXe.setModel(tblModel);
    }

    private List<BaiXe> timKiemTheXe(String theXe) throws Exception {
        BaiXeDao dao = new BaiXeDao();
        return dao.findByTheXe(txtTKVeXe.getText());
    }

    private List<BaiXe> timKiemBienSoXe(String theXe) throws Exception {
        BaiXeDao dao = new BaiXeDao();
        return dao.findByBienSoXe(txtTKBienSoXe.getText());
    }

    public void baiXe() {
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        try {
            BaiXeDao dao = new BaiXeDao();
            List<BaiXe> list = dao.findAll();
            tblModel.setRowCount(0);
            for (BaiXe bx : list) {
                tblModel.addRow(new Object[]{
                    bx.getTheXe(),
                    bx.getBienSoXe(),
                    format.format(bx.getThoiGianVao()),
                    bx.getLoaiXe(),
                    bx.getLoaiVe()
                });
            }

            tblModel.fireTableDataChanged();

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }

    private void initThoiGianBaiXe() {
        ClockThread th = new ClockThread(lblThoiGianVao);
        th.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbThoiGianBaiXe = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBienSoXe = new javax.swing.JTextField();
        txtTheXe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTKVeXe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTKBienSoXe = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtThoiGianVao = new javax.swing.JTextField();
        btnThemMoi = new javax.swing.JButton();
        btnXuatBen = new javax.swing.JButton();
        btnVaoBen = new javax.swing.JButton();
        cbxLoaiXe = new javax.swing.JComboBox<>();
        btnTTBaiXe = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBaiXe = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblThoiGianVao = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Quản Lý Bãi Xe");

        jLabel2.setText("Biển Số Xe:");

        jLabel6.setText("Thẻ Xe:");

        jLabel8.setText("Loại Xe:");

        jLabel3.setText("Tìm theo vé xe:");

        txtTKVeXe.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTKVeXeCaretUpdate(evt);
            }
        });

        jLabel4.setText("Tìm theo biển số xe:");

        txtTKBienSoXe.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTKBienSoXeCaretUpdate(evt);
            }
        });
        txtTKBienSoXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKBienSoXeActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/baiguixe/icons/search-icon-24.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel5.setText("Thời Gian Vào: ");

        btnThemMoi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/baiguixe/icons/new-icon-16.png"))); // NOI18N
        btnThemMoi.setText("Thêm Mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnXuatBen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXuatBen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/baiguixe/icons/raicon.jpg"))); // NOI18N
        btnXuatBen.setText("Xuất Bến");
        btnXuatBen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatBenActionPerformed(evt);
            }
        });

        btnVaoBen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVaoBen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/baiguixe/icons/vaoicon.png"))); // NOI18N
        btnVaoBen.setText("Vào Bến");
        btnVaoBen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaoBenActionPerformed(evt);
            }
        });

        cbxLoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe máy", "Ô tô" }));

        btnTTBaiXe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTTBaiXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/baiguixe/icons/thongtin.jpg"))); // NOI18N
        btnTTBaiXe.setText("Thông Tin Bãi Xe");
        btnTTBaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTBaiXeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(lbThoiGianBaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTheXe, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cbxLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtThoiGianVao, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnThemMoi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTTBaiXe))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTKVeXe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTKBienSoXe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btnVaoBen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btnXuatBen, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTKVeXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbThoiGianBaiXe)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTheXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTKBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThemMoi)
                                    .addComponent(btnTTBaiXe))
                                .addGap(33, 33, 33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtThoiGianVao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(14, 14, 14)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVaoBen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatBen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblBaiXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBaiXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBaiXeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBaiXe);

        jLabel7.setText("Thời Gian Hệ Thống:");

        lblThoiGianVao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblThoiGianVao.setText("jLabel5");
        lblThoiGianVao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblThoiGianVaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lblThoiGianVao, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblThoiGianVao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTKBienSoXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKBienSoXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTKBienSoXeActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String bienSoXe = txtTKBienSoXe.getText();
        String tkVeXe = txtTKVeXe.getText();
        List<BaiXe> list = null;
        BaiXeDao dao = new BaiXeDao();
        try {
            if (bienSoXe.equals("") && tkVeXe.equals("")) {
                list = dao.findAll();
            } else if (!bienSoXe.equals("") && tkVeXe.equals("")) {
                list = timKiemBienSoXe(bienSoXe);
            } else if (bienSoXe.equals("") && !tkVeXe.equals("")) {
                list = timKiemTheXe(tkVeXe);
            } else {
                List<BaiXe> listTemp = timKiemBienSoXe(bienSoXe);
                list = listTemp.stream()
                        .filter(bx -> bx.getTheXe().equals(tkVeXe))
                        .collect(Collectors.toCollection(ArrayList::new));
            }
            tblModel.setRowCount(0);
            SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
            for (BaiXe bx : list) {
                tblModel.addRow(new Object[]{
                    bx.getTheXe(),
                    bx.getBienSoXe(),
                    format.format(bx.getThoiGianVao()),
                    bx.getLoaiXe(),
                    bx.getLoaiVe()
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtTKVeXeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTKVeXeCaretUpdate
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTKVeXeCaretUpdate

    private void txtTKBienSoXeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTKBienSoXeCaretUpdate
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTKBienSoXeCaretUpdate

    private void btnVaoBenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaoBenActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtTheXe, sb, "Cần nhập Thẻ Xe");
        DataValidator.validateEmpty(txtBienSoXe, sb, "Cần nhập Biển Số Xe");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "lỗi");
            return;
        }
        try {
            BaiXe bx = null;
            BaiXeDao dao = new BaiXeDao();
            VeThangDao vtDao = new VeThangDao();
            String theXe = (String) txtTheXe.getText();
            if(!dao.checkTheXe(theXe)){
                throw new Exception("Thẻ Xe Đã Được Dùng");
            }
            List<BaiXe> listBaiXe = dao.findByBienSoXe(txtBienSoXe.getText());
            if(listBaiXe != null && listBaiXe.size() > 0){
                throw new Exception("Xe Đang Ở Trong Bến");
            }
            List<VeThang> tx = vtDao.findByTheXe(theXe);
            if (tx != null && tx.size() > 0) {
                VeThang txx = tx.get(0);
                if (!txx.getBienSoXe().equals(txtBienSoXe.getText())) {
                    throw new Exception("Biển số xe không đúng!");
                }
                if (!txx.getLoaiXe().equals(cbxLoaiXe.getSelectedItem())) {
                    throw new Exception(" Loại xe không đúng!");
                }
                if (txx.getNgayKetThuc().getTime() < new Date().getTime()) {
                    throw new Exception(" Thẻ xe đã hết hạn!");
                }
                Integer option = MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn thêm xe vào không?", "Hỏi");
                if (option == JOptionPane.OK_OPTION) {
                    bx = new BaiXe();
                    bx.setBienSoXe(txtBienSoXe.getText());
                    bx.setTheXe(txtTheXe.getText());
                    bx.setLoaiXe((String)cbxLoaiXe.getSelectedItem());
                    bx.setLoaiVe(LoaiVe.THANG.getName());
                    bx.setThoiGianVao(new Date());
                    if (dao.insert(bx)) {
                        MessageDialogHelper.showMessageDialog(parentForm, "Đã được lưu", "Thông báo");
                        capNhatTTBaiXe((String)cbxLoaiXe.getSelectedItem(), -1);
                    } else {
                        MessageDialogHelper.showMessageDialog(parentForm, "Không thể lưu", "Thông báo");
                    }
                }
            } else {
                bx = new BaiXe();
                bx.setBienSoXe(txtBienSoXe.getText());
                bx.setTheXe(txtTheXe.getText());
                bx.setLoaiXe((String)cbxLoaiXe.getSelectedItem());
                bx.setLoaiVe(LoaiVe.LUOT.getName());
                bx.setThoiGianVao(new Date());
                if (dao.insert(bx)) {
                    MessageDialogHelper.showMessageDialog(parentForm, "Đã được lưu", "Thông báo");
                    capNhatTTBaiXe((String)cbxLoaiXe.getSelectedItem(), -1);
                } else {
                    MessageDialogHelper.showMessageDialog(parentForm, "Không thể lưu", "Thông báo");
                }
            }
            baiXe();
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }

    }//GEN-LAST:event_btnVaoBenActionPerformed
    
    public void capNhatTTBaiXe(String loaiXe, int thayDoi) throws Exception{
        TTBaiXeDao dao = new TTBaiXeDao();
        TTBaiXe tt = dao.findByLoaiXe(loaiXe);
        int temp = tt.getSoChoTrong() + thayDoi;
        int soChoTrong = Math.max(0, temp);
        soChoTrong = Math.min(tt.getTongSoCho(), soChoTrong);
        tt.setSoChoTrong(soChoTrong);
        dao.update(tt);
    }
    
    private void btnXuatBenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatBenActionPerformed
        FormXuatBen xuatBen = new FormXuatBen(txtBienSoXe.getText(), this, formBaoCao);
        xuatBen.setVisible(true);
    }//GEN-LAST:event_btnXuatBenActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        setEdit(true);
        txtTheXe.setText("");
        txtBienSoXe.setText("");
        txtThoiGianVao.setText("");
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void lblThoiGianVaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblThoiGianVaoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblThoiGianVaoAncestorAdded

    private void setEdit(boolean editable){
        txtBienSoXe.setEditable(editable);
        txtTheXe.setEditable(editable);
        cbxLoaiXe.setEnabled(editable);
        txtThoiGianVao.setEditable(editable);
    }
    
    private void tblBaiXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBaiXeMouseClicked
        int row = tblBaiXe.getSelectedRow();
        if (row >= 0) {
            txtBienSoXe.setText(tblBaiXe.getValueAt(row, 1).toString());
            txtTheXe.setText(tblBaiXe.getValueAt(row, 0).toString());
            cbxLoaiXe.setSelectedItem(tblBaiXe.getValueAt(row, 3).toString());
            txtThoiGianVao.setText(tblBaiXe.getValueAt(row, 2).toString());
            setEdit(false);
            dataStatic = tblBaiXe.getValueAt(row, 0).toString();
            dataStatic1 = tblBaiXe.getValueAt(row, 3).toString();
            dataStatic2 = tblBaiXe.getValueAt(row, 4).toString();
            dataStatic3 = tblBaiXe.getValueAt(row, 2).toString();
        }
    }//GEN-LAST:event_tblBaiXeMouseClicked

    private void btnTTBaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTBaiXeActionPerformed
        new FormTTBaiXe().setVisible(true);
        
    }//GEN-LAST:event_btnTTBaiXeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTTBaiXe;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnVaoBen;
    private javax.swing.JButton btnXuatBen;
    private javax.swing.JComboBox<String> cbxLoaiXe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbThoiGianBaiXe;
    private javax.swing.JLabel lblThoiGianVao;
    private javax.swing.JTable tblBaiXe;
    private javax.swing.JTextField txtBienSoXe;
    private javax.swing.JTextField txtTKBienSoXe;
    private javax.swing.JTextField txtTKVeXe;
    private javax.swing.JTextField txtTheXe;
    private javax.swing.JTextField txtThoiGianVao;
    // End of variables declaration//GEN-END:variables

    
}
