package form;

import DataBase.DataValidator;
import DataBase.MessageDialogHelper;
import dao.BaiXeDao;
import dao.VeThangDao;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.VeThang;
import util.LoaiXe;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class FormQLVeThang extends javax.swing.JPanel {
    
    private FormMain parentForm;
    private DefaultTableModel tblModel;
    /**
     * Creates new form FormQLVeThang
     */
    public FormQLVeThang() {
        initComponents();
        initTable();
        veThang();
        cbxLoaiXe.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                int thanhTien = 0;
                if(e.getItem().equals(LoaiXe.OTO.getName())) thanhTien = LoaiXe.OTO.getThang();
                else thanhTien = LoaiXe.XEMAY.getThang();
                txtThanhToanVeThang.setText(String.valueOf(thanhTien));
                txtThanhToanVeThang.setEditable(false);
            }
        });
    }
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{
          "Thẻ Xe","Biển số xe", "Loại Xe","Ngày Đăng Kí","Ngày Kết Thúc","Thanh Toán"
        });
        tblVeThang.setModel(tblModel);
    }
    private void veThang(){
        try{
            VeThangDao dao = new VeThangDao();
            List<VeThang> list = dao.findAll();
            tblModel.setRowCount(0);
            for (VeThang vt : list) {
                tblModel.addRow(new Object[]{
                vt.getTheXe(), vt.getBienSoXe(), vt.getLoaiXe(), vt.getNgayDangKi(), vt.getNgayKetThuc(), vt.getThanhToan()});
            }
            tblModel.fireTableDataChanged();
        }      
    catch (Exception e){
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");   
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBienSoXe = new javax.swing.JTextField();
        txtNgayDangKi = new javax.swing.JTextField();
        txtNgayKetThuc = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnGiaHan = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTheXe = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbxLoaiXe = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtThanhToanVeThang = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTKBienSoXe = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVeThang = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Quản Lý Vé Tháng");

        jLabel3.setText("Biển Số Xe:");

        jLabel4.setText("Loại Xe:");

        jLabel7.setText("Ngày Đăng Kí:");

        jLabel8.setText("Ngày Kết Thúc:");

        txtNgayDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayDangKiActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/baiguixe/icons/new-icon-16.png"))); // NOI18N
        btnThem.setText("Thêm Mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/baiguixe/icons/Save-icon.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnGiaHan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGiaHan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/baiguixe/icons/giahan-6921.png"))); // NOI18N
        btnGiaHan.setText("Gia Hạn");
        btnGiaHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaHanActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/baiguixe/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel9.setText("Mã Thẻ Xe:");

        jLabel10.setText("Thông Tin:");

        cbxLoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ô tô", "Xe máy" }));
        cbxLoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiXeActionPerformed(evt);
            }
        });
        cbxLoaiXe.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbxLoaiXePropertyChange(evt);
            }
        });

        jLabel2.setText("Thanh Toán: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayDangKi)
                    .addComponent(txtNgayKetThuc)
                    .addComponent(txtBienSoXe)
                    .addComponent(txtTheXe, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxLoaiXe, 0, 213, Short.MAX_VALUE)
                    .addComponent(txtThanhToanVeThang))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGiaHan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTheXe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThem)
                                .addGap(16, 16, 16))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(btnGiaHan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbxLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnLuu)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnXoa)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThanhToanVeThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel12.setText("Biển Số Xe:");

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/baiguixe/icons/search-icon-16.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel12)
                .addGap(25, 25, 25)
                .addComponent(txtTKBienSoXe)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTKBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnTimKiem)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        tblVeThang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVeThang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVeThangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVeThang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgayDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayDangKiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayDangKiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        setEdit(true);
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        txtBienSoXe.setText("");
        txtTheXe.setText("");
        txtThanhToanVeThang.setText("");
        Date now = new Date();
        long oneMonth = (long)30 * 24 * 60 * 60 * 1000;
        txtNgayDangKi.setText(format.format(now));
        txtNgayKetThuc.setText(format.format(new Date(now.getTime() + oneMonth)));
        txtNgayDangKi.setEditable(false);
        txtNgayKetThuc.setEditable(false);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtBienSoXe, sb, "Chưa nhập biển số xe");
        DataValidator.validateEmpty(txtTheXe, sb, "Chưa nhập thẻ xe");
        DataValidator.validateEmpty(txtNgayDangKi, sb, "Chưa nhập ngày đăng kí");
        DataValidator.validateEmpty(txtNgayKetThuc, sb, "Chưa nhập ngày kết thúc");
        DataValidator.validateEmpty(txtThanhToanVeThang, sb, "Chưa nhập số tiền cần thanh toán");
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "lỗi");
            return;
        }
        try {
            VeThang vt = null;
            VeThangDao dao = new VeThangDao();
            BaiXeDao BXdao = new BaiXeDao();
            if(!BXdao.checkTheXe(txtTheXe.getText())){
                throw new Exception("Thẻ Xe Đã Được Dùng");
            }
            if (dao.findByTheXe(txtTheXe.getText()) != null) {
                Integer option = MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn lưu thẻ xe không?", "Hỏi");
                if (option == JOptionPane.OK_OPTION) {
                    vt = new VeThang();
                    vt.setTheXe(txtTheXe.getText());
                    vt.setBienSoXe(txtBienSoXe.getText());
                    vt.setLoaiXe((String) cbxLoaiXe.getSelectedItem());
                    vt.setNgayDangKi((java.util.Date) format.parse(txtNgayDangKi.getText()));
                    vt.setNgayKetThuc((java.util.Date) format.parse(txtNgayKetThuc.getText()));
                    vt.setThanhToan(Integer.parseInt(txtThanhToanVeThang.getText()));
                }
                if (dao.insert(vt)) {
                    MessageDialogHelper.showMessageDialog(parentForm, "Vé Tháng đã được lưu", "Thông báo");
                } else {
                    MessageDialogHelper.showMessageDialog(parentForm, "Vé Tháng không được lưu", "Thông báo");
                }
            }
            veThang();
        } catch (Exception e){
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
        
    }//GEN-LAST:event_btnLuuActionPerformed
      
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        VeThangDao dao = new VeThangDao();
        try {
            if(!txtTheXe.getText().equals("")){
                dao.delete(txtTheXe.getText());
                MessageDialogHelper.showMessageDialog(parentForm, "Xóa Thành Công!", "Thông Báo");
                txtTheXe.setText("");
                txtBienSoXe.setText("");
                txtNgayDangKi.setText("");
                txtNgayKetThuc.setText("");
                txtThanhToanVeThang.setText("");
            }else{
                MessageDialogHelper.showMessageDialog(parentForm, "Hãy chọn dòng cần xóa!", "Thông Báo");
            }
            veThang();
        } catch (Exception e) {
             MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        } 
    
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        try {
            VeThangDao dao = new VeThangDao();
            VeThang vt = dao.findByBienSoXe(txtTKBienSoXe.getText());
            if(vt != null){
                txtTheXe.setText(vt.getTheXe());
                txtBienSoXe.setText(vt.getBienSoXe());
                if(vt.getLoaiXe().equals(LoaiXe.OTO.getName())){
                    cbxLoaiXe.setSelectedIndex(0);
                }else if(vt.getLoaiXe().equals(LoaiXe.XEMAY.getName())){
                    cbxLoaiXe.setSelectedIndex(1);
                }
                txtNgayDangKi.setText(format.format(vt.getNgayDangKi()));
                txtNgayKetThuc.setText(format.format(vt.getNgayKetThuc()));
                txtThanhToanVeThang.setText(String.valueOf(vt.getThanhToan()));              
            }
            else {
                MessageDialogHelper.showMessageDialog(parentForm, "không tìm thấy biển số xe", "Thông Báo");
                }
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
        setEdit(false);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblVeThangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVeThangMouseClicked
        int row = tblVeThang.getSelectedRow();
        if (row >= 0) {
            txtTheXe.setText(tblVeThang.getValueAt(row, 0).toString());
            txtBienSoXe.setText(tblVeThang.getValueAt(row, 1).toString());
            cbxLoaiXe.setSelectedItem(tblVeThang.getValueAt(row, 2).toString());
            txtNgayDangKi.setText(tblVeThang.getValueAt(row, 3).toString());
            txtNgayKetThuc.setText(tblVeThang.getValueAt(row, 4).toString());
            txtThanhToanVeThang.setText(tblVeThang.getValueAt(row, 5).toString());
            setEdit(false);
        }
    }//GEN-LAST:event_tblVeThangMouseClicked

    private void btnGiaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaHanActionPerformed

        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        VeThang vt = null;
        VeThangDao dao = new VeThangDao();
        try {
            vt = dao.findByBienSoXe(txtBienSoXe.getText());
            if (vt != null) {
                Integer option = MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn gia hạn không?", "Hỏi");
                if (option == JOptionPane.OK_OPTION) {
                    long oneMonth = (long)30 * 24 * 60 * 60 * 1000;
                    Date date = new Date(new Date().getTime() + oneMonth);
                    int thanhToan = vt.getThanhToan();
                    if (vt.getLoaiXe().equals(LoaiXe.OTO.getName())) {
                        thanhToan += LoaiXe.OTO.getThang();
                    } else {
                        thanhToan += LoaiXe.XEMAY.getThang();
                    }
                    vt.setNgayKetThuc(date);
                    vt.setThanhToan(thanhToan);
                    if (dao.update(vt)) {
                        MessageDialogHelper.showMessageDialog(parentForm, "Vé tháng đã được cập nhật", "Thông báo");
                        txtNgayKetThuc.setText(format.format(vt.getNgayKetThuc()));
                        txtThanhToanVeThang.setText(String.valueOf(vt.getThanhToan()));
                    } else {
                        MessageDialogHelper.showMessageDialog(parentForm, "Vé Tháng chưa được cập nhật", "Thông báo");
                    }
                }
            }
            veThang();
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnGiaHanActionPerformed

    private void cbxLoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiXeActionPerformed
        
    }//GEN-LAST:event_cbxLoaiXeActionPerformed

    private void cbxLoaiXePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbxLoaiXePropertyChange
        
    }//GEN-LAST:event_cbxLoaiXePropertyChange
    
    private void setEdit(boolean editable){
        txtBienSoXe.setEditable(editable);
        txtTheXe.setEditable(editable);
        cbxLoaiXe.setEnabled(editable);
        txtNgayDangKi.setEditable(editable);
        txtNgayKetThuc.setEditable(editable);
        txtThanhToanVeThang.setEditable(editable);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiaHan;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxLoaiXe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblVeThang;
    private javax.swing.JTextField txtBienSoXe;
    private javax.swing.JTextField txtNgayDangKi;
    private javax.swing.JTextField txtNgayKetThuc;
    private javax.swing.JTextField txtTKBienSoXe;
    private javax.swing.JTextField txtThanhToanVeThang;
    private javax.swing.JTextField txtTheXe;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); 
    }
}
